///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeySignInResponseStatus = 'status';
const String _jsonKeySignInResponseMessage = 'message';
const String _jsonKeySignInResponseData = 'data';
const String _jsonKeySignInResponseDataId = 'id';
const String _jsonKeySignInResponseDataName = 'name';
const String _jsonKeySignInResponseDataEmail = 'email';
const String _jsonKeySignInResponseDataPhone = 'phone';
const String _jsonKeySignInResponseDataImage = 'image';
const String _jsonKeySignInResponseDataPoints = 'points';
const String _jsonKeySignInResponseDataCredit = 'credit';
const String _jsonKeySignInResponseDataToken = 'token';
class SignInResponseData {
/*
{
  "id": 55530,
  "name": "shimaa refaat",
  "email": "shimaa.refaat@ibm.com",
  "phone": "01141528",
  "image": "https://student.valuxapps.com/storage/uploads/users/eKfrWDbZuq_1684581339.jpeg",
  "points": 0,
  "credit": 0,
  "token": "el8U15TLpjDq8Mw8IAgnEM0OB2QobXQilQ0Dp4LC7PHT3mDvCQgwfdDn2kqkzcrQ9cg4c4"
}
*/

  int? id;
  String? name;
  String? email;
  String? phone;
  String? image;
  int? points;
  int? credit;
  String? token;

  SignInResponseData({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.image,
    this.points,
    this.credit,
    this.token,
  });
  SignInResponseData.fromJson(Map<String, dynamic> json) {
    id = int.tryParse(json[_jsonKeySignInResponseDataId]?.toString() ?? '');
    name = json[_jsonKeySignInResponseDataName]?.toString();
    email = json[_jsonKeySignInResponseDataEmail]?.toString();
    phone = json[_jsonKeySignInResponseDataPhone]?.toString();
    image = json[_jsonKeySignInResponseDataImage]?.toString();
    points = int.tryParse(json[_jsonKeySignInResponseDataPoints]?.toString() ?? '');
    credit = int.tryParse(json[_jsonKeySignInResponseDataCredit]?.toString() ?? '');
    token = json[_jsonKeySignInResponseDataToken]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeySignInResponseDataId] = id;
    data[_jsonKeySignInResponseDataName] = name;
    data[_jsonKeySignInResponseDataEmail] = email;
    data[_jsonKeySignInResponseDataPhone] = phone;
    data[_jsonKeySignInResponseDataImage] = image;
    data[_jsonKeySignInResponseDataPoints] = points;
    data[_jsonKeySignInResponseDataCredit] = credit;
    data[_jsonKeySignInResponseDataToken] = token;
    return data;
  }
}

class SignInResponse {
/*
{
  "status": true,
  "message": "تم تسجيل الدخول بنجاح",
  "data": {
    "id": 55530,
    "name": "shimaa refaat",
    "email": "shimaa.refaat@ibm.com",
    "phone": "01141528",
    "image": "https://student.valuxapps.com/storage/uploads/users/eKfrWDbZuq_1684581339.jpeg",
    "points": 0,
    "credit": 0,
    "token": "el8U15TLpjDq8Mw8IAgnEM0OB2QobXQilQ0Dp4LC7PHT3mDvCQgwfdDn2kqkzcrQ9cg4c4"
  }
}
*/

  bool? status;
  String? message;
  SignInResponseData? data;

  SignInResponse({
    this.status,
    this.message,
    this.data,
  });
  SignInResponse.fromJson(Map<String, dynamic> json) {
    status = json[_jsonKeySignInResponseStatus];
    message = json[_jsonKeySignInResponseMessage]?.toString();
    data = (json[_jsonKeySignInResponseData] != null && (json[_jsonKeySignInResponseData] is Map)) ? SignInResponseData.fromJson(json[_jsonKeySignInResponseData]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeySignInResponseStatus] = status;
    data[_jsonKeySignInResponseMessage] = message;
    if (data != null) {
      data[_jsonKeySignInResponseData] = this.data!.toJson();
    }
    return data;
  }
}
